spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/quizz_app
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: user
      password: 1234
  liquibase:
    change-log: database/changelog/changelog-master.xml